; Dwbryel-L2Voice — configuração do cliente
; Por Dwbryel | coloca este ficheiro ao lado de l2voice.dll e L2.exe

[voice]
enabled = 1
auto_connect = 1

; Local: 127.0.0.1 | VPS: ws://IP_PUBLICO:17667/ws
ws_url = ws://127.0.0.1:17667/ws

require_focus = 1
always_on = 0

ptt_proximity = 72
ptt_party     = 66
ptt_clan      = 78
ptt_ally      = 77

min_dist_cm = 500
max_dist_cm = 2500
master_volume = 100

ch_enabled_0 = 1
ch_enabled_1 = 1
ch_enabled_2 = 1
ch_enabled_3 = 1
ch_volume_0 = 100
ch_volume_1 = 100
ch_volume_2 = 100
ch_volume_3 = 100
active_tx_channel = 0

apm_aec = 1
apm_hpf = 1
apm_ns  = 1
apm_agc = 1
