# L2Voice VoIP — Dev ALN
# Gerado automaticamente pelo ModVozALN.exe

l2jalnvoice.enabled = true
l2jalnvoice.voice_server.urls = ws://127.0.0.1:17667/bridge

l2jalnvoice.redis.host = 127.0.0.1
l2jalnvoice.redis.port = 6379
l2jalnvoice.redis.channel = l2jalnvoice:events

l2jalnvoice.http.bind = 127.0.0.1
l2jalnvoice.http.port = 17668
l2jalnvoice.hmac.secret = L2Voice-FNuhNLIIAeQLjsFU10th4RnU

l2jalnvoice.position.hz = 10
l2jalnvoice.position.minDelta = 30
l2jalnvoice.gs.name = L2JALN-BR

# Fork (opcional) — o instalador preenche automaticamente para:
# L2jMega, aCis, RusaCis, L2jFrozen, L2JServer, L2Emu/EmuDev, Mobius
# Pack custom: descomente e ajuste:
# l2jalnvoice.fork.world = com.seupack.gameserver.model.L2World
# l2jalnvoice.fork.player = com.seupack.gameserver.model.actor.instance.L2PcInstance
# l2jalnvoice.fork.gameClient = com.seupack.gameserver.network.L2GameClient

# Pack detectada: BrProject / L2JBR (ext.mods)
l2jalnvoice.fork.world = ext.mods.gameserver.model.World
l2jalnvoice.fork.player = ext.mods.gameserver.model.actor.Player
l2jalnvoice.fork.gameClient = ext.mods.gameserver.network.GameClient
l2jalnvoice.fork.mmoConnection = ext.mods.commons.mmocore.MMOConnection
